env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  max-len: 0 
  indent: ["error", 4]
  no-tabs: 0
  react/prop-types: 0
  react/jsx-indent: 0
  react/no-array-index-key: 0
  react/no-children-prop: 0
  react/jsx-indent-props: ["error", 4]
  react/jsx-filename-extension: 0
  react/jsx-props-no-spreading: 0
  react/function-component-definition: 0
  max-classes-per-file: 0
  no-restricted-syntax: 0
  no-underscore-dangle: 0
  no-prototype-builtins: 0
  newline-per-chained-call: 0
  no-console: 0
  quotes: ["error", "double", { "avoidEscape": true }]
